### PR TITLE
Fix setting provided credentials

### LINKED ISSUE #20: Access params passed at initialization are ignored in favour of  ~/.aws/credentials
Initializing Cloudwatchlogger as follows:

```
l = CloudWatchLogger.new({access_key_id: '[redacted]', secret_access_key: '[redacted]'}, '/customer/main-site', 'stream-name', region: 'ap-northeast-1')
```

seems to ignore the credentials provided to the initializer and instead use the ones in ~/.aws/credentials.

### PR DESCRIPTION
**Pull request by mgz**
Fixes https://github.com/zshannon/cloudwatchlogger/issues/20

### CODE REVIEW

**Comment by troex** [comment]
@zshannon any chance to merge it? seams to be very obious "missing bang typo"

**Comment by skateman** [comment]
@zshannon can you please push a version with this fix?

**Comment by zshannon** [comment]
Sorry crew I don't remember how to use rubygems, been away from the ruby scene for many years now :( is there a way I can empower one of you to handle it?

**Comment by skateman** [comment]
Only if you give us ownership permissions via https://rubygems.org/gems/cloudwatchlogger/owners

**Comment by skateman** [comment]
You also need to bump version here in the codebase

**Comment by zshannon** [comment]
Published as `1.0.1`

**Pull request merged**
