### PR TITLE
Add exponential backoff algorithm when rate limit is exceeded

### PR DESCRIPTION
**Pull request by penguinpowernz**
By rescuing an `Aws::CloudWatchLogs::Errors::ThrottlingException` error we can avoid crashing the script by using an exponential backoff algo.  It may need to be a bit smarter; processing multiple messages from the queue at a time to prevent the `DeliveryThread` being rate limited multiple times thus holding up the process for a while after it's finished it's work - or worse, being killed when the process finishes and never sending the logs.

### CODE REVIEW

**Comment by penguinpowernz** [comment]
I have tested this quite a bit by using it, and I don't get those rate limited errors anymore.  However it does cause the messages to appear out of order in cloudwatch when something does get rate limited. Looking at how to fix this.

**Comment by cyrill62** [comment]
👍

**Comment by luizkowalski** [comment]
hey @penguinpowernz, did you find a solution?

**Comment by penguinpowernz** [comment]
No sorry, I ended up porting my tool to golang.

**Pull request closed without merging**
